### ISSUE TITLE
Comparator sometimes do not pulse whenever items are passing through

### ISSUE THREAD

**Issue by Tander** [bl4ckscor3/UnnamedSculkMod#1]
First of all, thank you for great mod! Great vanilla-like system, but I think comparator support can be improved.

The problem is, comparator doesn't detect when there are items in the Transmitter, until I put at least Speed 2 upgrade in transmitter. I think it's because items spend so little time in the block so they can't trigger comparator. Probably it has to be triggered directly each time item passes through.

It would be nice if this functionality still work reliably. It could be useful to build more smart system and be able to read activity on transporting lines, and maybe even dynamically manipulate the system with moving wool with pistons.

![изображение](https://user-images.githubusercontent.com/1059805/207227386-53baa333-e038-49e9-a983-e9ab8386626a.png)

**Comment by RedstoneDubstep** [comment]
Thank you for your report! You are correct, under normal circumstances comparators cannot detect items in Sculk Emitters or Transmitters because the items don't stay long enough in these blocks. For Sculk Transmitters, you can detect whether an item is currently stored via a conventional redstone signal (which generally updates fast enough to allow for e.g. reading activity consistently), however up to now this behaviour was not implemented for Sculk Emitters. 
Commit [c9637a5](https://github.com/bl4ckscor3/SculkTransporting/commit/c9637a5b163eef0153b9e11720fe7e535b616841) fixes this issue by introducing a conventional redstone signal for a Sculk Emitter holding an item.

**Comment by Tander** [comment]
This is a nice fix, thanks, but I hope in the future the mod will get more advanced redstone functionality. It would open so much possibilities.

For example, by monitoring a set of filtered Transmitters and blocking sculk paths with piston with wool, we could form reliable sequence of items we need (for crafting in vanilla, or for feeding botania flower in modded minecraft).
